"public final Foo f() throws Exception";
